### ISSUE TITLE
Uncaught TypeError in io_proxy.py line 216

### ISSUE THREAD

**Issue by edocod1** [dwash96/cecli#581]
cecli version: 0.100.8
Python version: 3.12.12
Platform: Linux-7.0.12-201.fc44.x86_64-x86_64-with-glibc2.43
Python implementation: CPython
Virtual environment: Yes
OS: Linux 7.0.12-201.fc44.x86_64 (64bit)
Git version: git version 2.54.0

Configuration:
```yaml
35turbo: False
4: False
4_turbo: False
4o: False
add_gitignore_files: False
agent_config: None
agent_model: None
alias: None
analytics: None
analytics_disable: True
analytics_log: None
analytics_posthog_host: None
apply: None
apply_clipboard_edits: False
assistant_output_color: #0088ff
attribute_author: None
attribute_co_authored_by: True
attribute_commit_message_author: False
attribute_commit_message_committer: False
attribute_committer: None
auto_accept_architect: True
auto_commits: True
auto_lint: True
auto_load: False
auto_save: False
auto_save_session_name: auto-save
auto_test: False
cache_keepalive_pings: 0
cache_prompts: False
chat_language: None
check_model_accepts_settings: True
check_update: True
code_theme: default
command_prefix: None
commit: False
commit_language: None
commit_prompt: None
completion_menu_bg_color: None
completion_menu_color: None
completion_menu_current_bg_color: None
completion_menu_current_color: None
config: None
context_compaction_max_tokens: 65536
context_compaction_summary_tokens: 4096
copy_paste: False
cost_limit: None
custom: None
dark_mode: False
debug: False
deepseek: False
detect_urls: True
dirty_commits: True
disable_playwright: False
disable_scraping: False
dry_run: False
edit_format: None
editor: None
editor_edit_format: None
editor_model: None
enable_context_compaction: True
encoding: utf-8
exempt_paths: []
exit: False
fancy_input: True
file: None
file_diffs: True
files: []
git: True
git_commit_verify: False
gitignore: True
haiku: False
hooks: None
just_check_update: False
light_mode: False
line_endings: platform
linear_output: True
lint: False
lint_cmd: []
list_models: None
llm_history_file: None
load: None
map_cache_dir: .
map_max_line_length: 100
map_memory_cache: False
map_multiplier_no_files: 2
map_refresh: auto
map_tokens: None
max_chat_history_tokens: None
max_reflections: 3
mcp_servers: None
mcp_servers_file_deprecated: None
mcp_servers_files: []
mcp_transport: stdio
message: None
message_file: None
mini: False
model: openai/glm-5.1
model_metadata_file: .cecli.model.metadata.json
model_overrides: None
model_overrides_file: .cecli.model.overrides.yml
model_settings_file: .cecli.model.settings.yml
multiline: False
notifications: True
notifications_command: None
o1_mini: False
o1_preview: False
openai_api_base: https://api.z.ai/api/coding/paas/v4
openai_api_deployment_id: None
openai_api_type: None
openai_api_version: None
openai_organization_id: None
opus: False
preserve_todo_list: False
pretty: True
read: None
reasoning_effort: None
retries: None
rules: None
security_config: None
session_encrypt: False
set_env: []
shell_completions: None
show_diffs: False
show_model_warnings: False
show_prompts: False
show_release_notes: None
show_repo_map: False
show_speed: False
show_thinking: True
skip_sanity_check_repo: False
sonnet: False
stream: True
subtree_only: False
suggest_shell_commands: True
terminal_setup: False
test: False
test_cmd: []
thinking_tokens: None
timeout: None
tool_error_color: #FF2222
tool_output_color: None
tool_warning_color: #FFA500
tui: False
tui_config: None
tweak_responses: False
upgrade: False
use_enhanced_map: True
use_reminders: True
user_input_color: #00cc00
verbose: False
verify_ssl: True
vim: False
voice_format: wav
voice_input_device: None
voice_language: en
watch_files: False
weak_model: openai/glm-4.7
workspace_name: None
workspaces: None
yes_always: None
yes_always_commands: False
```

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "cecli", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 494, in main
    return asyncio.run(
           ^^^^^^^^^^^^
  File "runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main.py", line 1300, in main_async
    await coder.run()
  File "base_coder.py", line 1470, in run
    return await self._run_linear(with_message, preproc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "io_proxy.py", line 216, in stop_output_task
    await task
TypeError: Coder.__init__() got an unexpected keyword argument 'total_cost'

```

Hello I'm using z.ai though these configs:

```

openai-api-key: cacc728dc0b71aced5e104eeb66343e0.IHjmRfwwVl2fReDI
openai-api-base: https://api.z.ai/api/coding/paas/v4
model: "openai/glm-5.1"
weak-model: "openai/glm-4.7"

```

This error happens when there is a switch between architect mode and edit mode. I assume something about calculating the total cost of the architect + edit interaction causes that error.

**Comment by dwash96** [comment]
Ah yeah, I moved cost tracking to a global singleton when I added subagents, I'll address it in the next patch update

**Comment by dwash96** [comment]
Added `v0.100.9rc1` release candidate version to PyPi to patch this over while I work on other items for the full 0.100.9 release
